"""initial migration

Revision ID: 3c8d7853057c
Revises:
Create Date: 2023-09-09 13:57:20.265720

"""
from alembic import op
import sqlalchemy as sa
from app import bcrypt


# revision identifiers, used by Alembic.
revision = "3c8d7853057c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rfid_id", sa.String(length=11), nullable=False),
        sa.Column("alias", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        sa.UniqueConstraint("rfid_id"),
    )
    op.create_table(
        "checkpoints",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sentries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("national_id", sa.String(length=8), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone_no", sa.String(length=13), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("national_id"),
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("shift_start", sa.Integer(), nullable=False),
        sa.Column("shift_end", sa.Integer(), nullable=False),
        sa.Column("_sentries_on_duty", sa.Text(), nullable=False),
        sa.Column("_circuit", sa.Text(), nullable=False),
        sa.Column("_path_freqs", sa.Text(), nullable=False),
        sa.Column("_alarms", sa.Text(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shift_start"),
    )
    supervisor_table = op.create_table(
        "supervisors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "ptrl_paths",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chkpt_src", sa.Integer(), nullable=False),
        sa.Column("chkpt_dest", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chkpt_dest"],
            ["checkpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chkpt_src"],
            ["checkpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chkpt_src", "chkpt_dest", name="_ptrl_path_uc"),
    )
    # ### end Alembic commands ###

    # creating the supervisor

    op.bulk_insert(
        supervisor_table,
        [
            {
                "email": "supervisor@company.com",
                "password": bcrypt.generate_password_hash("Master0Pass").decode("utf-8"),
            }
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ptrl_paths")
    op.drop_table("supervisors")
    op.drop_table("shifts")
    op.drop_table("sentries")
    op.drop_table("checkpoints")
    op.drop_table("cards")
    # ### end Alembic commands ###
